Release/0.2.0
snowplow/iglu-ruby-client pull request #14
Opened 2017-11-03 13:07 UTC by oguzhanunlu

- [ ] Fix SchemaVer.parse_schemaver parses invalid SchemaVer #7 

- [ ] Update README markdown in according with CommonMark #13 

- [ ] Fix invalid cache-lookup #11 

- [ ] Add retry-policy #10 

- [ ] Add configurable cache max-age for schemas #6 

- [ ] Switch to rubygems provider #5 

- [ ] Bump version in README (https://github.com/snowplow/iglu-ruby-client/blame/master/README.md#L47)

- [ ] Add CHANGELOG

2017-11-03 15:37 UTC, alexanderdean commented
Missing space in commit message "Add configurable cache max-age for schemas (close#6)"

2017-11-03 15:38 UTC, alexanderdean commented
"Bump release-image version to 0.2.0 in README" belongs in the "Prepare for release" commit

2017-11-03 16:30 UTC, oguzhanunlu commented
Thanks @alexanderdean , just fixed them.

2017-11-06 08:30 UTC, chuwy requested changes
Hey @oguzhanunlu,

This is a good start! I left few comments - ones regarding new `cacheTtl` are most important - Iglu Scala Client uses seconds as TTL and we cannot have clients with inconsistent configuration. Also, tests are very important.

2017-11-06 08:30 UTC, chuwy commented on .travis.yml
> +
Please, add a `condition` from previous version as well (and `.travis/is_valid_tag.rb` as it is required), I should have warn you about it. 

Without `condition` pushing could result in a quite serious issue when we would push `0.3.0.beta` tag, but `0.3.0` by mistake remains in source code - as a result `0.3.0` will be published to RubyGems, which is in fact should have been `0.3.0.beta` (by our intentions, e.g. git tag). And we cannot delete releases from RubyGems, which means we'll leave invalid release on RubyGems.

We have this situation right now: `0.2.0.beta` is on RubyGems, but in source code there's `0.2.0.beta.2`. It's quite ok for beta-releases, but should never happen for final releases. `condition` makes us safe here.

2017-11-06 08:30 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +      @cache_ttl = 1 # hour
`cacheTtl` by no means should be in hours - this is always seconds.

2017-11-06 08:30 UTC, chuwy commented on lib/iglu-client/version.rb
> +  CLIENT_VERSION = '0.2.0.beta.2'
As I mentioned in first comment - there's only `0.2.0.beta` published on RubyGems. Version in latest tag and asset on RubyGems should always be compatible.

2017-11-06 08:30 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +    attr_reader :registries, :cache, :cache_ttl
I expect to see test coverage for this new feature with **at least** following cases:

* Parse resolver config JSON with `cacheTtl`
* Invalidate schema after some period of time (make sure new fetch attempt is undertaken). You can use `sleep` here
* Confirm that no new fetch attempts are undertaken after small enough period

2017-11-06 10:32 UTC, chuwy commented
Also, regarding tests - I would expect we can test configuration with both:

1. `cacheTtl: null`
2. missing `cacheTtl`

These are both valid `resolver_config/1-0-2`, but might have different representations in Ruby.

2017-11-07 15:24 UTC, oguzhanunlu commented
@chuwy I think 0.2.0.beta.3 meets your review except a test confirming that only one fetch operation is performed before cacheTtl expires. I spent too much time unnecessarily for that test and wanted to release 0.2.0.beta.3 for your review. In the meantime, I'll figure out that test.

2017-11-08 10:09 UTC, chuwy requested changes
Ok, nice. We need one more iteration fixing cache implementation and hopefully that one missing unit-test.

2017-11-08 10:09 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +      @cacheTtl = cacheTtl.nil? ? 60 : cacheTtl
I don't think we can afford default values here. If `cacheTtl` isn't set then our cache simply does not expire and lives in application until it is terminated.

2017-11-08 10:09 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +          else # backward compliance
Not sure what does `backward compliance` mean here. Are we returning `[schema, time]` from `lookup_schema` function? Cache mechanics should be a part of library internals and user never cares of timestamp, therefore `lookup_schema` should always return only `schema`.

2017-11-08 10:09 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +               end
Broken indentation.

2017-11-08 10:09 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +          else # backward compliance
Also, please make return type clear in function's description.

2017-11-08 10:09 UTC, chuwy commented on lib/iglu-client/resolver.rb
> -        # cache_size = data[:cacheSize]
No commented code should be in production code.

2017-11-08 10:09 UTC, chuwy commented on spec/iglu-client/resolver_spec.rb
> +  it 'correctly parses a standard resolver configuration containing cacheTtl (not null)' do
This is amount of unit-tests I expected for this feature. Very good.

2017-11-08 10:09 UTC, chuwy commented on spec/iglu-client/resolver_spec.rb
> +    expect(resolver.cache.size).to eq(0)
I commented above that this is not correct cache-implementation. Without this test I would not notice it - one more advantage of good test-coverage - you show your expectations to other developers.

2017-11-08 10:09 UTC, chuwy commented on lib/iglu-client/resolver.rb
> +                 @cache.delete(schema_key)
We need not just delete cached item, but replace it with new.

Whole point of cache is that your cached item *can* be outdated after TTL and therefore you need to *refresh* it. In this implementation it is *always* outdated after TTL.

2017-11-08 10:09 UTC, chuwy commented on spec/iglu-client/resolver_spec.rb
> +    expect(resolver.cacheTtl).to eq(60)
Also commented above - we should not have default `cacheTtl`.

2017-11-08 10:09 UTC, chuwy commented on spec/iglu-client/schema_key_spec.rb
> +    expect { Iglu::SchemaVer.parse_schemaver("2.0.3") }.to raise_error(Iglu::IgluError)
Let's also add few expectations for multiple-digits versions. They're correct, e.g. `10-0-11` should be correct, `10-a-1` should be not correct.

2017-11-08 13:47 UTC, oguzhanunlu commented on lib/iglu-client/resolver.rb
> +          else # backward compliance
It actually returns schema, not array but I made a mistake here, thanks for noticing!

2017-11-09 10:38 UTC, alexanderdean commented
Hey @chuwy - I am working on a "materiality clause" for when a release needs a blog post or not - but definitely this one doesn't need a blog post. Just put the release paragraphs into the Discourse release announcement.

2017-11-09 10:49 UTC, chuwy commented
Thanks @alexanderdean! I agree.

Hey @oguzhanunlu, are you sure this PR refers to branch in our repository? I still see `oguzhanunlu:release/0.2.0` in header. If this is "our" branch, then please proceed to release process as we discussed in chat - I'm unlocking master branch.

2017-11-09 10:57 UTC, oguzhanunlu commented
Closing since this PR refers to my fork's branch, will open a new PR now.

2017-11-09 10:57 UTC, closed without merging